// This file will be auto-generated by running:
// pnpm db:types
// 
// For now, we define placeholder types based on the schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          role: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          role?: string
          created_at?: string
          updated_at?: string
        }
      }
      expense_drafts: {
        Row: {
          id: string
          user_id: string
          employee_id: string | null
          amount: number
          category: string
          description: string | null
          vendor_name: string | null
          vendor_id: string | null
          job_order_id: string | null
          is_overhead: boolean
          expense_date: string
          expense_time: string | null
          gps_latitude: number | null
          gps_longitude: number | null
          gps_accuracy: number | null
          receipt_id: string | null
          ocr_confidence: number | null
          requires_review: boolean
          sync_status: string
          local_id: string | null
          synced_at: string | null
          bkk_record_id: string | null
          approval_status: string
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          created_at: string
          updated_at: string
          created_from: string
        }
        Insert: {
          id?: string
          user_id: string
          employee_id?: string | null
          amount: number
          category: string
          description?: string | null
          vendor_name?: string | null
          vendor_id?: string | null
          job_order_id?: string | null
          is_overhead?: boolean
          expense_date?: string
          expense_time?: string | null
          gps_latitude?: number | null
          gps_longitude?: number | null
          gps_accuracy?: number | null
          receipt_id?: string | null
          ocr_confidence?: number | null
          requires_review?: boolean
          sync_status?: string
          local_id?: string | null
          synced_at?: string | null
          bkk_record_id?: string | null
          approval_status?: string
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          created_at?: string
          updated_at?: string
          created_from?: string
        }
        Update: {
          id?: string
          user_id?: string
          employee_id?: string | null
          amount?: number
          category?: string
          description?: string | null
          vendor_name?: string | null
          vendor_id?: string | null
          job_order_id?: string | null
          is_overhead?: boolean
          expense_date?: string
          expense_time?: string | null
          gps_latitude?: number | null
          gps_longitude?: number | null
          gps_accuracy?: number | null
          receipt_id?: string | null
          ocr_confidence?: number | null
          requires_review?: boolean
          sync_status?: string
          local_id?: string | null
          synced_at?: string | null
          bkk_record_id?: string | null
          approval_status?: string
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          created_at?: string
          updated_at?: string
          created_from?: string
        }
      }
      job_orders: {
        Row: {
          id: string
          job_number: string
          customer_name: string
          origin: string
          destination: string
          status: string
        }
        Insert: {
          id?: string
          job_number: string
          customer_name: string
          origin: string
          destination: string
          status?: string
        }
        Update: {
          id?: string
          job_number?: string
          customer_name?: string
          origin?: string
          destination?: string
          status?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Convenience types
export type UserProfile = Tables<'user_profiles'>
export type ExpenseDraft = Tables<'expense_drafts'>
export type JobOrder = Tables<'job_orders'>

// User roles
export type UserRole = 
  | 'owner'
  | 'director'
  | 'finance_manager'
  | 'finance'
  | 'operations_manager'
  | 'ops'
  | 'operations'
  | 'engineer'

export const ALLOWED_ROLES: UserRole[] = [
  'owner',
  'director',
  'finance_manager',
  'finance',
  'operations_manager',
  'ops',
  'operations',
  'engineer',
]
